### ISSUE TITLE
bug ArrayUtils::isoData

### ISSUE THREAD

**Issue by shahamer** [mariolpantunes/utils#2]
When the input array for the function isoData contains values which are all the same (i.e., array contains same values, e.g., array={.5, .5}) the function gets stuck in an infinite loop. 
The reason for the infinite loop is that either cat or cbt will be zero (as all values of the array are the same, they are either below t or above). 
This will cause mat or mbt to be NaN (as they are divided by the zero of cat or cbt).
This in turn will cause the new calculated t (= (mat + mbt) / 2.0) to also be NaN.
Which will return to the while (while (t != ot)) -- however, NaN!=NaN, and thus we are stuck in an infinite loop.

My suggestion is to add after the inner for loop (i.e., before calculating mat and mbt) the following:
               if (cat == 0 || cbt == 0) {
                    // this means all array values are the same
                    assert Arrays.stream(array).allMatch(i -> i == array[0]);
                    return t; // return mean
                }

**Comment by mariolpantunes** [comment]
Thanks for pointing out the error, it should be fixed in this commit.
