### ISSUE TITLE
bug ArrayUtils::allEqual

### ISSUE THREAD

**Issue by shahamer** [mariolpantunes/utils#5]
The function ArrayUtils::allEqual calls: 
return equalTo(a, bIdx, len, a[bIdx], 0);

However, the last variable (i.e., 0) is double eps. 
Setting eps=0 means, with high probability, that double comparison will fail. 

For example, even: 
allEqual(new double[] { 0.5 }) would fail, as: 0.5-0.5=0 but *not* <0.
Changing 
MathUtils::MathUtils.java from 
return Math.abs(a - b) < eps
to 
return Math.abs(a - b) <= eps

will still not help as eps==0 is not sensitive enough to double subtraction. 

Solution: 
(a) either use a fixed (i.e., constant) positive double (e.g., 0.0001)
(b) use something like: eps= 5 * max(StrictMath.ulp(a), StrictMath.ulp(b))

**Comment by mariolpantunes** [comment]
Again thanks for your insight.
It helps me to improve my code and learn new things.

I ended up using simple equality (==) in the allEquals methods, if this method is not working properly in some cases please let me known.

I also added a new method to verify if to double values are equal, maybe this can be used instead of simple equality. Although this method is more expensive computationally.

Keep me posted.

**Comment by shahamer** [comment]
Happy to help :-)

Using simple equality (in ArrayUtils::allEqual ... rv = a[i] == a[i + 1]) might not work. As you know, double representation (following the IEEE standard) allows some epsilon.
Therefore, simple applications producing distances and then looking for an elbow/knee have a good probability to fail. 
Take for example the cosine distance between two equal vectors: a=b=[1.0, 1.0].
One function might do a direct cosine computation of (which shortly results in): 
    double d1 = (1. * 1. + 1. * 1.) / Math.sqrt(1. * 1. + 1. * 1.) / Math.sqrt(1. * 1. + 1. * 1.)
while another function might do:
    double d2 = a==b? 1.0 : cosine(a, b);

You'll get:
d1 = 0.9999999999999999
d2 = 1.0

Sending these numbers to elbow/knee will then fail on ArrayUtils::allEqual.


PS:
Small remark on MathUtils::round(final double n):
why not simply calling Math.round(n)? the function caller did not ask for any ndp (number of decimal places) == why getting into unnecessary heavy calls to Math.abs, Math.log10, and BigDecimal operations?

**Comment by shahamer** [comment]
Hello again,
The entire discussion regarding allEqual(..) was cause by the code added to ArrayUtils::isoData(..) (i.e., if (!allEqual(array, bIdx, len))).
I can also see that you've marked out (at ArrayUtils::isoData(..)):
//mat = (cat > 0) ? mat / cat: 0.0;
//mbt = (cbt > 0) ? mbt / cbt: 0.0;

While the above code might not be very sexy code, I think it is still a better solution. 
Firstly, it is better on the run-time side, as no need to O(N) scan the array for allEqual(..) -- and if not all equal then scan the array again for deviation of the mean. 
Secondly, it defuse the definition problem of allEqual (i.e., to what Eps to set it), as it is naturally uses the mean to "understand" whether array is allEqual.

Thus, I recommend removing the allEqual call and remove comment of mat=..  and mbt=...

**Comment by mariolpantunes** [comment]
You are right.
The latest commit should fix everything.
The IsoData method should be robust right now.

**Comment by shahamer** [comment]
The following code still throws an exception
        final double[] X = new double[] { 1, 2 };
        final double[] Y = new double[] { 0.1934, 0.193 };
        new DFDT().elbow(X, Y);

**Comment by mariolpantunes** [comment]
Cfd needs at least 3 values. A minimal working example require at least 4 values. However i will fix the code to return the correct exception ir a default value

**Comment by mariolpantunes** [comment]
Sure. I will fix it. Thanks for all the support
